"""Write an Ollama Modelfile that pins the labelling settings in a named model.

The prompt is NOT baked in by default: with gemma4 on Ollama 0.35.1 a SYSTEM line in the
Modelfile produced different, worse output than sending the same text as a system message
(README Section 7.7). Send prompts/v3.txt with each request instead. --bake-system restores
the old behaviour for testing.

    python build_modelfile.py --model gemma4:12b --ctx 16384 > Modelfile
    ollama create aptx-labeler -f Modelfile

The base model must already be pulled; this adds no download.
"""
import argparse
from pathlib import Path

p = argparse.ArgumentParser()
p.add_argument('--model', default='gemma4:12b')
p.add_argument('--prompt', default='v3')
p.add_argument('--ctx', type=int, default=16384)
p.add_argument('--predict', type=int, default=500)
p.add_argument('--bake-system', action='store_true')
a = p.parse_args()

lines = ['# APT Explorer stage 2 labeller. Generated by build_modelfile.py.',
         f'FROM {a.model}',
         'PARAMETER temperature 0',
         f'PARAMETER num_ctx {a.ctx}',
         f'PARAMETER num_predict {a.predict}']
if a.bake_system:
    prompt = (Path(__file__).resolve().parent.parent / 'prompts' / f'{a.prompt}.txt').read_text(encoding='utf-8').strip()
    assert '"""' not in prompt
    lines += ['SYSTEM """', prompt, '"""']
print('\n'.join(lines))
